def generate_email_draft(result: dict) -> str:
    meeting = result.get("meeting", {})
    open_items = result.get("open_items", [])
    closed_items = result.get("closed_items", [])
    watch_items = result.get("watch_items", [])

    date = meeting.get("date", "Unknown")
    duration = meeting.get("duration", "Unknown")
    attendees = ", ".join(meeting.get("attendees", []))

    lines = []
    lines.append(f"FOR Meeting Action Items — {date}")
    lines.append("=" * 50)
    lines.append(f"Duration: {duration}")
    lines.append(f"Attendees: {attendees}")
    lines.append("")

    # Open items
    lines.append(f"OPEN ACTION ITEMS ({len(open_items)})")
    lines.append("-" * 40)
    if open_items:
        for item in open_items:
            req_id = item.get("request_id", "—")
            owner = item.get("current_owner", "Unknown")
            priority = item.get("priority", "Medium")
            status = item.get("status", "")
            actions = item.get("action_items", "")
            due = item.get("due_date", "Not specified")
            carry = item.get("carry_over_flag", False)
            consecutive = item.get("consecutive_meetings", 1)

            carry_tag = f"  ⚠ CARRY-OVER ({consecutive} meetings)" if carry else ""
            lines.append(f"{req_id} | Owner: {owner} | Priority: {priority} | Due: {due}{carry_tag}")
            lines.append(f"  Status: {status}")
            if actions:
                lines.append(f"  Actions: {actions}")
            lines.append("")
    else:
        lines.append("None")
        lines.append("")

    # Flagged items
    flagged = [i for i in open_items if i.get("flags")]
    if flagged:
        lines.append(f"🚩 FLAGGED ITEMS ({len(flagged)})")
        lines.append("-" * 40)
        for item in flagged:
            req_id = item.get("request_id", "—")
            flag_notes = item.get("flag_notes", "")
            flags = ", ".join(item.get("flags", []))
            lines.append(f"{req_id} — [{flags}]")
            if flag_notes:
                lines.append(f"  {flag_notes}")
            lines.append("")

    # Carry-overs
    carry_overs = [i for i in open_items if i.get("carry_over_flag")]
    if carry_overs:
        lines.append(f"🔄 CARRY-OVERS — No Status Change in 3+ Meetings ({len(carry_overs)})")
        lines.append("-" * 40)
        for item in carry_overs:
            req_id = item.get("request_id", "—")
            consecutive = item.get("consecutive_meetings", 3)
            owner = item.get("current_owner", "Unknown")
            lines.append(f"{req_id} — {consecutive} consecutive meetings | Owner: {owner}")
        lines.append("")

    # Closed items
    if closed_items:
        lines.append(f"✅ CLOSED THIS MEETING ({len(closed_items)})")
        lines.append("-" * 40)
        for item in closed_items:
            req_id = item.get("request_id", "—")
            resolution = item.get("resolution", "")
            resolved_by = item.get("resolved_by", "Unknown")
            lines.append(f"{req_id} — Resolved by {resolved_by}: {resolution}")
        lines.append("")

    # Watch items
    if watch_items:
        lines.append(f"👀 WATCH ITEMS — Not Yet Formal FOR Requests ({len(watch_items)})")
        lines.append("-" * 40)
        for item in watch_items:
            desc = item.get("description", "")
            raised = item.get("raised_by", "Unknown")
            next_step = item.get("next_step", "Monitor")
            lines.append(f"• {desc}")
            lines.append(f"  Raised by: {raised} | Next step: {next_step}")
        lines.append("")

    lines.append("—")
    lines.append("Generated by FOR Meeting Assistant")

    return "\n".join(lines)
